spring.application.name=livraria

spring.datasource.url=jdbc:postgresql://localhost:5432/bookflowdb
spring.datasource.username=user_book
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true